variables:
  NS_SERVICE_NAME: server
stages:
  - build
  - deploy

docker-build:
  image: docker:18.09
  stage: build
  services:
    - docker:18.09-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  only:
    - release
  before_script:
    - echo $CI_BUILD_TOKEN | docker login -u "${CI_REGISTRY_USER}" --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" --build-arg CI_JOB_USER=${CI_JOB_USER_TOKEN} --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} .
    - docker push "$CI_REGISTRY_IMAGE:latest"
  after_script:
    - docker logout ${CI_REGISTRY}

