// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/proto/auth.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	CorporationId        string   `protobuf:"bytes,2,opt,name=corporationId,proto3" json:"corporationId,omitempty"`
	IpAddress            string   `protobuf:"bytes,3,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cfb59be99677c78, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *RegisterRequest) GetCorporationId() string {
	if m != nil {
		return m.CorporationId
	}
	return ""
}

func (m *RegisterRequest) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

type RegisterResponse struct {
	IsAuth               bool                            `protobuf:"varint,1,opt,name=isAuth,proto3" json:"isAuth,omitempty"`
	AppId                string                          `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId,omitempty"`
	AuthType             int32                           `protobuf:"varint,4,opt,name=authType,proto3" json:"authType,omitempty"`
	Corporations         []*RegisterResponse_Corporation `protobuf:"bytes,3,rep,name=corporations,proto3" json:"corporations,omitempty"`
	Languages            []*RegisterResponse_Language    `protobuf:"bytes,5,rep,name=languages,proto3" json:"languages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cfb59be99677c78, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetIsAuth() bool {
	if m != nil {
		return m.IsAuth
	}
	return false
}

func (m *RegisterResponse) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *RegisterResponse) GetAuthType() int32 {
	if m != nil {
		return m.AuthType
	}
	return 0
}

func (m *RegisterResponse) GetCorporations() []*RegisterResponse_Corporation {
	if m != nil {
		return m.Corporations
	}
	return nil
}

func (m *RegisterResponse) GetLanguages() []*RegisterResponse_Language {
	if m != nil {
		return m.Languages
	}
	return nil
}

type RegisterResponse_Corporation struct {
	Id                   string                                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid                 string                                     `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	AppId                string                                     `protobuf:"bytes,7,opt,name=appId,proto3" json:"appId,omitempty"`
	Name                 string                                     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SubDomain            string                                     `protobuf:"bytes,4,opt,name=sub_domain,json=subDomain,proto3" json:"sub_domain,omitempty"`
	Companies            []*RegisterResponse_Corporation_Company    `protobuf:"bytes,5,rep,name=companies,proto3" json:"companies,omitempty"`
	Connections          []*RegisterResponse_Corporation_Connection `protobuf:"bytes,6,rep,name=connections,proto3" json:"connections,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *RegisterResponse_Corporation) Reset()         { *m = RegisterResponse_Corporation{} }
func (m *RegisterResponse_Corporation) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse_Corporation) ProtoMessage()    {}
func (*RegisterResponse_Corporation) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cfb59be99677c78, []int{1, 0}
}

func (m *RegisterResponse_Corporation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse_Corporation.Unmarshal(m, b)
}
func (m *RegisterResponse_Corporation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse_Corporation.Marshal(b, m, deterministic)
}
func (m *RegisterResponse_Corporation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse_Corporation.Merge(m, src)
}
func (m *RegisterResponse_Corporation) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse_Corporation.Size(m)
}
func (m *RegisterResponse_Corporation) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse_Corporation.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse_Corporation proto.InternalMessageInfo

func (m *RegisterResponse_Corporation) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RegisterResponse_Corporation) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RegisterResponse_Corporation) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *RegisterResponse_Corporation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterResponse_Corporation) GetSubDomain() string {
	if m != nil {
		return m.SubDomain
	}
	return ""
}

func (m *RegisterResponse_Corporation) GetCompanies() []*RegisterResponse_Corporation_Company {
	if m != nil {
		return m.Companies
	}
	return nil
}

func (m *RegisterResponse_Corporation) GetConnections() []*RegisterResponse_Corporation_Connection {
	if m != nil {
		return m.Connections
	}
	return nil
}

type RegisterResponse_Corporation_Company struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse_Corporation_Company) Reset()         { *m = RegisterResponse_Corporation_Company{} }
func (m *RegisterResponse_Corporation_Company) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse_Corporation_Company) ProtoMessage()    {}
func (*RegisterResponse_Corporation_Company) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cfb59be99677c78, []int{1, 0, 0}
}

func (m *RegisterResponse_Corporation_Company) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse_Corporation_Company.Unmarshal(m, b)
}
func (m *RegisterResponse_Corporation_Company) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse_Corporation_Company.Marshal(b, m, deterministic)
}
func (m *RegisterResponse_Corporation_Company) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse_Corporation_Company.Merge(m, src)
}
func (m *RegisterResponse_Corporation_Company) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse_Corporation_Company.Size(m)
}
func (m *RegisterResponse_Corporation_Company) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse_Corporation_Company.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse_Corporation_Company proto.InternalMessageInfo

func (m *RegisterResponse_Corporation_Company) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RegisterResponse_Corporation_Company) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RegisterResponse_Corporation_Company) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RegisterResponse_Corporation_Connection struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 string   `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	Instance             string   `protobuf:"bytes,3,opt,name=instance,proto3" json:"instance,omitempty"`
	Database             string   `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	Username             string   `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Driver               string   `protobuf:"bytes,7,opt,name=driver,proto3" json:"driver,omitempty"`
	StringConnection     string   `protobuf:"bytes,8,opt,name=string_connection,json=stringConnection,proto3" json:"string_connection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse_Corporation_Connection) Reset() {
	*m = RegisterResponse_Corporation_Connection{}
}
func (m *RegisterResponse_Corporation_Connection) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse_Corporation_Connection) ProtoMessage()    {}
func (*RegisterResponse_Corporation_Connection) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cfb59be99677c78, []int{1, 0, 1}
}

func (m *RegisterResponse_Corporation_Connection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse_Corporation_Connection.Unmarshal(m, b)
}
func (m *RegisterResponse_Corporation_Connection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse_Corporation_Connection.Marshal(b, m, deterministic)
}
func (m *RegisterResponse_Corporation_Connection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse_Corporation_Connection.Merge(m, src)
}
func (m *RegisterResponse_Corporation_Connection) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse_Corporation_Connection.Size(m)
}
func (m *RegisterResponse_Corporation_Connection) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse_Corporation_Connection.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse_Corporation_Connection proto.InternalMessageInfo

func (m *RegisterResponse_Corporation_Connection) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *RegisterResponse_Corporation_Connection) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *RegisterResponse_Corporation_Connection) GetInstance() string {
	if m != nil {
		return m.Instance
	}
	return ""
}

func (m *RegisterResponse_Corporation_Connection) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *RegisterResponse_Corporation_Connection) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterResponse_Corporation_Connection) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterResponse_Corporation_Connection) GetDriver() string {
	if m != nil {
		return m.Driver
	}
	return ""
}

func (m *RegisterResponse_Corporation_Connection) GetStringConnection() string {
	if m != nil {
		return m.StringConnection
	}
	return ""
}

type RegisterResponse_Language struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Alias                string   `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Acronym              string   `protobuf:"bytes,4,opt,name=acronym,proto3" json:"acronym,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse_Language) Reset()         { *m = RegisterResponse_Language{} }
func (m *RegisterResponse_Language) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse_Language) ProtoMessage()    {}
func (*RegisterResponse_Language) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cfb59be99677c78, []int{1, 1}
}

func (m *RegisterResponse_Language) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse_Language.Unmarshal(m, b)
}
func (m *RegisterResponse_Language) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse_Language.Marshal(b, m, deterministic)
}
func (m *RegisterResponse_Language) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse_Language.Merge(m, src)
}
func (m *RegisterResponse_Language) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse_Language.Size(m)
}
func (m *RegisterResponse_Language) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse_Language.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse_Language proto.InternalMessageInfo

func (m *RegisterResponse_Language) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RegisterResponse_Language) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterResponse_Language) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *RegisterResponse_Language) GetAcronym() string {
	if m != nil {
		return m.Acronym
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "proto.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "proto.RegisterResponse")
	proto.RegisterType((*RegisterResponse_Corporation)(nil), "proto.RegisterResponse.Corporation")
	proto.RegisterType((*RegisterResponse_Corporation_Company)(nil), "proto.RegisterResponse.Corporation.Company")
	proto.RegisterType((*RegisterResponse_Corporation_Connection)(nil), "proto.RegisterResponse.Corporation.Connection")
	proto.RegisterType((*RegisterResponse_Language)(nil), "proto.RegisterResponse.Language")
}

func init() {
	proto.RegisterFile("internal/proto/auth.proto", fileDescriptor_7cfb59be99677c78)
}

var fileDescriptor_7cfb59be99677c78 = []byte{
	// 482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xdd, 0x8a, 0x13, 0x31,
	0x14, 0xa6, 0xb3, 0x9d, 0xb6, 0x73, 0xea, 0xcf, 0x1a, 0x44, 0xc6, 0x41, 0xa1, 0xac, 0x5e, 0x14,
	0x16, 0x66, 0x41, 0xef, 0x85, 0xb2, 0x82, 0x14, 0xbc, 0x90, 0xe0, 0xb5, 0x4b, 0x3a, 0x09, 0xdd,
	0x60, 0x27, 0x89, 0xf9, 0x51, 0xfa, 0x0a, 0x3e, 0x96, 0xef, 0xe2, 0x7b, 0x48, 0x32, 0x93, 0xc9,
	0xac, 0xec, 0x42, 0xaf, 0x26, 0x5f, 0xce, 0x39, 0xdf, 0x39, 0xdf, 0x37, 0x27, 0xf0, 0x92, 0x0b,
	0xcb, 0xb4, 0x20, 0x87, 0x2b, 0xa5, 0xa5, 0x95, 0x57, 0xc4, 0xd9, 0xdb, 0x3a, 0x1c, 0x51, 0x1e,
	0x3e, 0x17, 0xdf, 0xe1, 0x29, 0x66, 0x7b, 0x6e, 0x2c, 0xd3, 0x98, 0xfd, 0x70, 0xcc, 0x58, 0xf4,
	0x1c, 0x72, 0xa2, 0xd4, 0x96, 0x96, 0x93, 0xd5, 0x64, 0x5d, 0xe0, 0x0e, 0xa0, 0xb7, 0xf0, 0xb8,
	0x91, 0x5a, 0x49, 0x4d, 0x2c, 0x97, 0x62, 0x4b, 0xcb, 0x2c, 0x44, 0xef, 0x5e, 0xa2, 0x57, 0x50,
	0x70, 0xb5, 0xa1, 0x54, 0x33, 0x63, 0xca, 0xb3, 0x90, 0x91, 0x2e, 0x2e, 0x7e, 0xcf, 0xe1, 0x3c,
	0x75, 0x33, 0x4a, 0x0a, 0xc3, 0xd0, 0x0b, 0x98, 0x71, 0xb3, 0x71, 0xf6, 0x36, 0xf4, 0x5b, 0xe0,
	0x1e, 0xa5, 0x31, 0xb2, 0xf1, 0x18, 0x15, 0x2c, 0xbc, 0x88, 0xaf, 0x47, 0xc5, 0xca, 0xe9, 0x6a,
	0xb2, 0xce, 0xf1, 0x80, 0xd1, 0x27, 0x78, 0x34, 0x9a, 0xc6, 0xf7, 0x3f, 0x5b, 0x2f, 0xdf, 0xbd,
	0xe9, 0x04, 0xd7, 0xff, 0x37, 0xae, 0xaf, 0x53, 0x2e, 0xbe, 0x53, 0x88, 0x3e, 0x40, 0x71, 0x20,
	0x62, 0xef, 0xc8, 0x9e, 0x99, 0x32, 0x0f, 0x2c, 0xab, 0x87, 0x58, 0x3e, 0xf7, 0x89, 0x38, 0x95,
	0x54, 0x7f, 0xa6, 0xb0, 0x1c, 0xb1, 0xa3, 0x27, 0x90, 0xf1, 0x68, 0x67, 0xc6, 0x29, 0x42, 0x30,
	0x75, 0x8e, 0x47, 0x65, 0xe1, 0x9c, 0xe4, 0xce, 0xc7, 0x72, 0x11, 0x4c, 0x05, 0x69, 0x59, 0x6f,
	0x65, 0x38, 0xa3, 0xd7, 0x00, 0xc6, 0xed, 0x6e, 0xa8, 0x6c, 0x09, 0x17, 0xc1, 0x84, 0x02, 0x17,
	0xc6, 0xed, 0x3e, 0x86, 0x0b, 0xb4, 0x85, 0xa2, 0x91, 0xad, 0x22, 0x82, 0x0f, 0xc3, 0x5f, 0x9e,
	0x60, 0x41, 0x7d, 0x1d, 0x8a, 0x8e, 0x38, 0x55, 0xa3, 0x2f, 0xb0, 0x6c, 0xa4, 0x10, 0xac, 0xe9,
	0xfc, 0x9c, 0x05, 0xb2, 0xfa, 0x34, 0xb2, 0x58, 0x86, 0xc7, 0x14, 0xd5, 0x06, 0xe6, 0x7d, 0x9f,
	0x91, 0x29, 0xf9, 0x83, 0xa6, 0xdc, 0x23, 0xbf, 0xfa, 0x3b, 0x01, 0x48, 0xf4, 0x81, 0x46, 0x0d,
	0xde, 0x2a, 0x5f, 0xa2, 0xa4, 0xb6, 0x91, 0xc6, 0x9f, 0xfd, 0xd2, 0x70, 0x61, 0x2c, 0x11, 0x4d,
	0xa4, 0x1a, 0xb0, 0x8f, 0x51, 0x62, 0xc9, 0x8e, 0x18, 0xd6, 0x7b, 0x39, 0x60, 0x1f, 0x73, 0xc6,
	0xbf, 0x9f, 0x96, 0x95, 0x79, 0x17, 0x8b, 0xd8, 0xc7, 0x14, 0x31, 0xe6, 0x97, 0xd4, 0xb4, 0x9c,
	0x75, 0xb1, 0x88, 0xfd, 0x4a, 0x53, 0xcd, 0x7f, 0x32, 0xdd, 0xff, 0xcc, 0x1e, 0xa1, 0x4b, 0x78,
	0x66, 0xac, 0xe6, 0x62, 0x7f, 0x93, 0x3c, 0x29, 0x17, 0x21, 0xe5, 0xbc, 0x0b, 0x24, 0x61, 0xd5,
	0x37, 0x58, 0xc4, 0xdd, 0xba, 0xcf, 0xab, 0x30, 0x54, 0x36, 0x5a, 0x0b, 0xbf, 0x40, 0x07, 0x4e,
	0xe2, 0xb3, 0xeb, 0x00, 0x2a, 0x61, 0x4e, 0x1a, 0x2d, 0xc5, 0xb1, 0xed, 0xd5, 0x45, 0xb8, 0x9b,
	0x85, 0xdf, 0xf8, 0xfe, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x7a, 0x9e, 0x30, 0x24, 0x04,
	0x00, 0x00,
}
