// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/proto/exchange-rate.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExchangeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangeRequest) Reset()         { *m = ExchangeRequest{} }
func (m *ExchangeRequest) String() string { return proto.CompactTextString(m) }
func (*ExchangeRequest) ProtoMessage()    {}
func (*ExchangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d26184c7c3bffc79, []int{0}
}

func (m *ExchangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeRequest.Unmarshal(m, b)
}
func (m *ExchangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeRequest.Marshal(b, m, deterministic)
}
func (m *ExchangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeRequest.Merge(m, src)
}
func (m *ExchangeRequest) XXX_Size() int {
	return xxx_messageInfo_ExchangeRequest.Size(m)
}
func (m *ExchangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeRequest proto.InternalMessageInfo

type Exchange struct {
	Buy                  float64  `protobuf:"fixed64,1,opt,name=buy,proto3" json:"buy,omitempty"`
	Sale                 float64  `protobuf:"fixed64,2,opt,name=sale,proto3" json:"sale,omitempty"`
	Date                 string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Exchange) Reset()         { *m = Exchange{} }
func (m *Exchange) String() string { return proto.CompactTextString(m) }
func (*Exchange) ProtoMessage()    {}
func (*Exchange) Descriptor() ([]byte, []int) {
	return fileDescriptor_d26184c7c3bffc79, []int{1}
}

func (m *Exchange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Exchange.Unmarshal(m, b)
}
func (m *Exchange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Exchange.Marshal(b, m, deterministic)
}
func (m *Exchange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Exchange.Merge(m, src)
}
func (m *Exchange) XXX_Size() int {
	return xxx_messageInfo_Exchange.Size(m)
}
func (m *Exchange) XXX_DiscardUnknown() {
	xxx_messageInfo_Exchange.DiscardUnknown(m)
}

var xxx_messageInfo_Exchange proto.InternalMessageInfo

func (m *Exchange) GetBuy() float64 {
	if m != nil {
		return m.Buy
	}
	return 0
}

func (m *Exchange) GetSale() float64 {
	if m != nil {
		return m.Sale
	}
	return 0
}

func (m *Exchange) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type ExchangeResponse struct {
	Sunat                []*Exchange `protobuf:"bytes,1,rep,name=sunat,proto3" json:"sunat,omitempty"`
	Sbs                  []*Exchange `protobuf:"bytes,2,rep,name=sbs,proto3" json:"sbs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ExchangeResponse) Reset()         { *m = ExchangeResponse{} }
func (m *ExchangeResponse) String() string { return proto.CompactTextString(m) }
func (*ExchangeResponse) ProtoMessage()    {}
func (*ExchangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d26184c7c3bffc79, []int{2}
}

func (m *ExchangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeResponse.Unmarshal(m, b)
}
func (m *ExchangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeResponse.Marshal(b, m, deterministic)
}
func (m *ExchangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeResponse.Merge(m, src)
}
func (m *ExchangeResponse) XXX_Size() int {
	return xxx_messageInfo_ExchangeResponse.Size(m)
}
func (m *ExchangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeResponse proto.InternalMessageInfo

func (m *ExchangeResponse) GetSunat() []*Exchange {
	if m != nil {
		return m.Sunat
	}
	return nil
}

func (m *ExchangeResponse) GetSbs() []*Exchange {
	if m != nil {
		return m.Sbs
	}
	return nil
}

func init() {
	proto.RegisterType((*ExchangeRequest)(nil), "proto.ExchangeRequest")
	proto.RegisterType((*Exchange)(nil), "proto.Exchange")
	proto.RegisterType((*ExchangeResponse)(nil), "proto.ExchangeResponse")
}

func init() {
	proto.RegisterFile("internal/proto/exchange-rate.proto", fileDescriptor_d26184c7c3bffc79)
}

var fileDescriptor_d26184c7c3bffc79 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0xbf, 0x0a, 0xc2, 0x30,
	0x10, 0x87, 0x49, 0x63, 0x45, 0xcf, 0xa1, 0x35, 0x53, 0xc6, 0x1a, 0x10, 0xba, 0xd8, 0x82, 0xbe,
	0x82, 0xbe, 0x40, 0x67, 0x97, 0x54, 0x0f, 0x15, 0x4a, 0x5a, 0x7b, 0x29, 0xe8, 0xdb, 0x4b, 0xae,
	0xfe, 0x59, 0x9c, 0xf2, 0xf1, 0x7d, 0x3f, 0xc2, 0x81, 0xb9, 0x39, 0x8f, 0xbd, 0xb3, 0x4d, 0xd9,
	0xf5, 0xad, 0x6f, 0x4b, 0x7c, 0x9c, 0xae, 0xd6, 0x5d, 0x70, 0xd3, 0x5b, 0x8f, 0x05, 0x3b, 0x15,
	0xf3, 0x63, 0x96, 0x90, 0x1c, 0xde, 0xb5, 0xc2, 0xfb, 0x80, 0xe4, 0xcd, 0x1e, 0x66, 0x1f, 0xa5,
	0x52, 0x90, 0xf5, 0xf0, 0xd4, 0x22, 0x13, 0xb9, 0xa8, 0x02, 0x2a, 0x05, 0x13, 0xb2, 0x0d, 0xea,
	0x88, 0x15, 0x73, 0x70, 0x67, 0xeb, 0x51, 0xcb, 0x4c, 0xe4, 0xf3, 0x8a, 0xd9, 0x1c, 0x21, 0xfd,
	0x7d, 0x4c, 0x5d, 0xeb, 0x08, 0xd5, 0x1a, 0x62, 0x1a, 0x9c, 0xf5, 0x5a, 0x64, 0x32, 0x5f, 0x6c,
	0x93, 0xf1, 0x94, 0xe2, 0xbb, 0x1b, 0xab, 0x5a, 0x81, 0xa4, 0x9a, 0x74, 0xf4, 0x7f, 0x14, 0x5a,
	0x3d, 0x65, 0xb9, 0x7b, 0x05, 0x00, 0x00, 0xff, 0xff, 0xd8, 0xf1, 0x44, 0x49, 0xea, 0x00, 0x00,
	0x00,
}
