// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/proto/messages.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessagesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessagesRequest) Reset()         { *m = MessagesRequest{} }
func (m *MessagesRequest) String() string { return proto.CompactTextString(m) }
func (*MessagesRequest) ProtoMessage()    {}
func (*MessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad09ee8a5c2738e2, []int{0}
}

func (m *MessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagesRequest.Unmarshal(m, b)
}
func (m *MessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagesRequest.Marshal(b, m, deterministic)
}
func (m *MessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesRequest.Merge(m, src)
}
func (m *MessagesRequest) XXX_Size() int {
	return xxx_messageInfo_MessagesRequest.Size(m)
}
func (m *MessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesRequest proto.InternalMessageInfo

type Message struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Severity             int32    `protobuf:"varint,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	LanguageId           int32    `protobuf:"varint,4,opt,name=languageId,proto3" json:"languageId,omitempty"`
	Language             string   `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	Cause                string   `protobuf:"bytes,6,opt,name=cause,proto3" json:"cause,omitempty"`
	CorrectiveAction     string   `protobuf:"bytes,7,opt,name=correctiveAction,proto3" json:"correctiveAction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad09ee8a5c2738e2, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Message) GetSeverity() int32 {
	if m != nil {
		return m.Severity
	}
	return 0
}

func (m *Message) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Message) GetLanguageId() int32 {
	if m != nil {
		return m.LanguageId
	}
	return 0
}

func (m *Message) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Message) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

func (m *Message) GetCorrectiveAction() string {
	if m != nil {
		return m.CorrectiveAction
	}
	return ""
}

type MessagesResponse struct {
	Messages             []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MessagesResponse) Reset()         { *m = MessagesResponse{} }
func (m *MessagesResponse) String() string { return proto.CompactTextString(m) }
func (*MessagesResponse) ProtoMessage()    {}
func (*MessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad09ee8a5c2738e2, []int{2}
}

func (m *MessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagesResponse.Unmarshal(m, b)
}
func (m *MessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagesResponse.Marshal(b, m, deterministic)
}
func (m *MessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesResponse.Merge(m, src)
}
func (m *MessagesResponse) XXX_Size() int {
	return xxx_messageInfo_MessagesResponse.Size(m)
}
func (m *MessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesResponse proto.InternalMessageInfo

func (m *MessagesResponse) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*MessagesRequest)(nil), "proto.MessagesRequest")
	proto.RegisterType((*Message)(nil), "proto.Message")
	proto.RegisterType((*MessagesResponse)(nil), "proto.MessagesResponse")
}

func init() {
	proto.RegisterFile("internal/proto/messages.proto", fileDescriptor_ad09ee8a5c2738e2)
}

var fileDescriptor_ad09ee8a5c2738e2 = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x89, 0xed, 0x76, 0xeb, 0x08, 0x5a, 0x07, 0x0f, 0x83, 0xa0, 0x2c, 0x7b, 0x5a, 0x3c,
	0xb4, 0xa0, 0x77, 0xc1, 0xa3, 0x07, 0x2f, 0xf9, 0x07, 0x31, 0x1d, 0x96, 0x40, 0x4d, 0x6a, 0x92,
	0x2d, 0xf8, 0x33, 0xfd, 0x47, 0xe2, 0x34, 0xbb, 0x0a, 0x3d, 0x25, 0xdf, 0x7b, 0xf3, 0x12, 0xe6,
	0xc1, 0x9d, 0xf3, 0x99, 0xa3, 0x37, 0xbb, 0xcd, 0x3e, 0x86, 0x1c, 0x36, 0x1f, 0x9c, 0x92, 0xe9,
	0x39, 0xad, 0x05, 0xb1, 0x92, 0xa3, 0xbd, 0x86, 0xab, 0xb7, 0x62, 0x68, 0xfe, 0x1c, 0x38, 0xe5,
	0xf6, 0x5b, 0x41, 0x5d, 0x34, 0x44, 0x98, 0xdb, 0xb0, 0x65, 0x52, 0x8d, 0xea, 0x2a, 0x2d, 0x77,
	0xbc, 0x85, 0x65, 0xe2, 0x03, 0x47, 0x97, 0xbf, 0xe8, 0x4c, 0xf4, 0x89, 0x91, 0xa0, 0x2e, 0xff,
	0xd0, 0xac, 0x51, 0xdd, 0xb9, 0x1e, 0x11, 0xef, 0x01, 0x76, 0xc6, 0xf7, 0x83, 0xe9, 0xf9, 0x75,
	0x4b, 0x73, 0xc9, 0xfd, 0x53, 0x7e, 0x5f, 0x1d, 0x89, 0x2a, 0x89, 0x4e, 0x8c, 0x37, 0x50, 0x59,
	0x33, 0x24, 0xa6, 0x85, 0x18, 0x47, 0xc0, 0x07, 0x58, 0xd9, 0x10, 0x23, 0xdb, 0xec, 0x0e, 0xfc,
	0x62, 0xb3, 0x0b, 0x9e, 0x6a, 0x19, 0x38, 0xd1, 0xdb, 0x67, 0x58, 0xfd, 0xad, 0x99, 0xf6, 0xc1,
	0x4b, 0x7e, 0x39, 0x76, 0x42, 0xaa, 0x99, 0x75, 0x17, 0x8f, 0x97, 0xc7, 0x6e, 0xd6, 0x65, 0x54,
	0x4f, 0xfe, 0xfb, 0x42, 0x8c, 0xa7, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x51, 0x4c, 0x0f, 0x4e,
	0x55, 0x01, 0x00, 0x00,
}
