// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/proto/notify.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NotifyType int32

const (
	NotifyType_ERROR   NotifyType = 0
	NotifyType_SUCCESS NotifyType = 1
	NotifyType_WARNING NotifyType = 2
	NotifyType_INFO    NotifyType = 3
)

var NotifyType_name = map[int32]string{
	0: "ERROR",
	1: "SUCCESS",
	2: "WARNING",
	3: "INFO",
}

var NotifyType_value = map[string]int32{
	"ERROR":   0,
	"SUCCESS": 1,
	"WARNING": 2,
	"INFO":    3,
}

func (x NotifyType) String() string {
	return proto.EnumName(NotifyType_name, int32(x))
}

func (NotifyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c120169a403953e7, []int{0}
}

type NotifyRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	ReceiveNotify        bool     `protobuf:"varint,2,opt,name=receiveNotify,proto3" json:"receiveNotify,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyRequest) Reset()         { *m = NotifyRequest{} }
func (m *NotifyRequest) String() string { return proto.CompactTextString(m) }
func (*NotifyRequest) ProtoMessage()    {}
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c120169a403953e7, []int{0}
}

func (m *NotifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyRequest.Unmarshal(m, b)
}
func (m *NotifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyRequest.Marshal(b, m, deterministic)
}
func (m *NotifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyRequest.Merge(m, src)
}
func (m *NotifyRequest) XXX_Size() int {
	return xxx_messageInfo_NotifyRequest.Size(m)
}
func (m *NotifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyRequest proto.InternalMessageInfo

func (m *NotifyRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *NotifyRequest) GetReceiveNotify() bool {
	if m != nil {
		return m.ReceiveNotify
	}
	return false
}

type Notify struct {
	Type                 NotifyType `protobuf:"varint,1,opt,name=type,proto3,enum=proto.NotifyType" json:"type,omitempty"`
	Message              []byte     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Time                 int64      `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	UserId               int32      `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Test                 string     `protobuf:"bytes,5,opt,name=test,proto3" json:"test,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Notify) Reset()         { *m = Notify{} }
func (m *Notify) String() string { return proto.CompactTextString(m) }
func (*Notify) ProtoMessage()    {}
func (*Notify) Descriptor() ([]byte, []int) {
	return fileDescriptor_c120169a403953e7, []int{1}
}

func (m *Notify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notify.Unmarshal(m, b)
}
func (m *Notify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notify.Marshal(b, m, deterministic)
}
func (m *Notify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notify.Merge(m, src)
}
func (m *Notify) XXX_Size() int {
	return xxx_messageInfo_Notify.Size(m)
}
func (m *Notify) XXX_DiscardUnknown() {
	xxx_messageInfo_Notify.DiscardUnknown(m)
}

var xxx_messageInfo_Notify proto.InternalMessageInfo

func (m *Notify) GetType() NotifyType {
	if m != nil {
		return m.Type
	}
	return NotifyType_ERROR
}

func (m *Notify) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Notify) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Notify) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Notify) GetTest() string {
	if m != nil {
		return m.Test
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.NotifyType", NotifyType_name, NotifyType_value)
	proto.RegisterType((*NotifyRequest)(nil), "proto.NotifyRequest")
	proto.RegisterType((*Notify)(nil), "proto.Notify")
}

func init() {
	proto.RegisterFile("internal/proto/notify.proto", fileDescriptor_c120169a403953e7)
}

var fileDescriptor_c120169a403953e7 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8e, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xdd, 0xe6, 0x4f, 0xdb, 0xd1, 0x4a, 0x1c, 0x44, 0x16, 0xbc, 0x84, 0xa2, 0x10, 0x3c,
	0xb4, 0xa0, 0x47, 0x4f, 0x52, 0xaa, 0x04, 0x21, 0x85, 0x89, 0xe2, 0x39, 0xda, 0x51, 0x02, 0x36,
	0x59, 0xb3, 0x5b, 0x21, 0x1f, 0xc1, 0x6f, 0x2d, 0xce, 0x2a, 0xd2, 0xd3, 0xbc, 0xdf, 0xcc, 0xf0,
	0xde, 0x83, 0xd3, 0xba, 0x71, 0xdc, 0x35, 0xd5, 0xfb, 0xdc, 0x74, 0xad, 0x6b, 0xe7, 0x4d, 0xeb,
	0xea, 0xd7, 0x7e, 0x26, 0x80, 0x91, 0x8c, 0xe9, 0x3d, 0x4c, 0x0a, 0x59, 0x13, 0x7f, 0x6c, 0xd9,
	0x3a, 0x3c, 0x86, 0xa8, 0x32, 0x26, 0x5f, 0x6b, 0x95, 0xaa, 0x6c, 0x4c, 0x1e, 0xf0, 0x0c, 0x26,
	0x1d, 0xbf, 0x70, 0xfd, 0xc9, 0xfe, 0x5b, 0x0f, 0x52, 0x95, 0x8d, 0x68, 0x77, 0x39, 0xfd, 0x52,
	0x10, 0x7b, 0x89, 0xe7, 0x10, 0xba, 0xde, 0xb0, 0xb8, 0x1c, 0x5e, 0x1e, 0xf9, 0xd0, 0x99, 0x3f,
	0x3e, 0xf4, 0x86, 0x49, 0xce, 0xa8, 0x61, 0xb8, 0x61, 0x6b, 0xab, 0x37, 0x16, 0xc7, 0x03, 0xfa,
	0x43, 0x44, 0x08, 0x5d, 0xbd, 0x61, 0x1d, 0xa4, 0x2a, 0x0b, 0x48, 0x34, 0x9e, 0x40, 0xbc, 0xb5,
	0xdc, 0xe5, 0x6b, 0x1d, 0xa6, 0x2a, 0x8b, 0xe8, 0x97, 0xe4, 0x97, 0xad, 0xd3, 0x91, 0x54, 0x16,
	0x7d, 0x71, 0x0d, 0xf0, 0x9f, 0x86, 0x63, 0x88, 0x96, 0x44, 0x2b, 0x4a, 0xf6, 0x70, 0x1f, 0x86,
	0xe5, 0xe3, 0x62, 0xb1, 0x2c, 0xcb, 0x44, 0xfd, 0xc0, 0xd3, 0x0d, 0x15, 0x79, 0x71, 0x97, 0x0c,
	0x70, 0x04, 0x61, 0x5e, 0xdc, 0xae, 0x92, 0xe0, 0x39, 0x96, 0xba, 0x57, 0xdf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x52, 0xc3, 0xb6, 0x8f, 0x42, 0x01, 0x00, 0x00,
}
