// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/proto/service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Corporacion          string   `protobuf:"bytes,1,opt,name=corporacion,proto3" json:"corporacion,omitempty"`
	Inicio               string   `protobuf:"bytes,2,opt,name=inicio,proto3" json:"inicio,omitempty"`
	Fin                  string   `protobuf:"bytes,3,opt,name=fin,proto3" json:"fin,omitempty"`
	Moneda               string   `protobuf:"bytes,4,opt,name=moneda,proto3" json:"moneda,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_3474577474948ca0, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetCorporacion() string {
	if m != nil {
		return m.Corporacion
	}
	return ""
}

func (m *Request) GetInicio() string {
	if m != nil {
		return m.Inicio
	}
	return ""
}

func (m *Request) GetFin() string {
	if m != nil {
		return m.Fin
	}
	return ""
}

func (m *Request) GetMoneda() string {
	if m != nil {
		return m.Moneda
	}
	return ""
}

type Response struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_3474577474948ca0, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_3474577474948ca0, []int{2}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Request)(nil), "proto.Request")
	proto.RegisterType((*Response)(nil), "proto.Response")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
}

func init() {
	proto.RegisterFile("internal/proto/service.proto", fileDescriptor_3474577474948ca0)
}

var fileDescriptor_3474577474948ca0 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x59, 0x6b, 0xb7, 0x75, 0x14, 0x95, 0x1c, 0x64, 0x11, 0x0f, 0x25, 0x27, 0x7b, 0x69,
	0x41, 0x9f, 0xa0, 0x07, 0xe9, 0x7d, 0xf7, 0x09, 0xd2, 0xec, 0x08, 0x81, 0xee, 0x4c, 0x4c, 0x66,
	0x05, 0x1f, 0xc2, 0x77, 0x96, 0x4d, 0xc2, 0xe2, 0x45, 0x3c, 0x25, 0xdf, 0xfc, 0x1f, 0xc9, 0xfc,
	0xf0, 0xe4, 0x48, 0x30, 0x90, 0x39, 0xef, 0x7d, 0x60, 0xe1, 0x7d, 0xc4, 0xf0, 0xe9, 0x2c, 0xee,
	0x12, 0xa9, 0x65, 0x3a, 0xf4, 0x00, 0xab, 0x16, 0x3f, 0x46, 0x8c, 0xa2, 0x36, 0x70, 0x6d, 0x39,
	0x78, 0x0e, 0xc6, 0x3a, 0xa6, 0xa6, 0xda, 0x54, 0xcf, 0x57, 0xed, 0xef, 0x91, 0x7a, 0x80, 0xda,
	0x91, 0xb3, 0x8e, 0x9b, 0x8b, 0x14, 0x16, 0x52, 0xf7, 0xb0, 0x78, 0x77, 0xd4, 0x2c, 0xd2, 0x70,
	0xba, 0x4e, 0xe6, 0xc0, 0x84, 0xbd, 0x69, 0x2e, 0xb3, 0x99, 0x49, 0x6b, 0x58, 0xb7, 0x18, 0x3d,
	0x53, 0xc4, 0xc9, 0x09, 0x18, 0xc7, 0xb3, 0x94, 0xaf, 0x0a, 0xe9, 0x15, 0x2c, 0xdf, 0x06, 0x2f,
	0x5f, 0x2f, 0xdf, 0x15, 0xc0, 0xa1, 0xef, 0xbb, 0xbc, 0xb7, 0xda, 0xc2, 0xfa, 0x88, 0xd2, 0x8d,
	0x64, 0x44, 0xdd, 0xe4, 0x16, 0xbb, 0x24, 0x3e, 0xde, 0x15, 0x9a, 0x9f, 0xde, 0x42, 0x7d, 0x44,
	0x39, 0x78, 0xaf, 0x6e, 0xe7, 0x28, 0x95, 0xfc, 0x4b, 0xed, 0x4e, 0xf1, 0x5f, 0xf5, 0x54, 0x27,
	0x7e, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x3b, 0xda, 0x5d, 0x59, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AddServiceClient is the client API for AddService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddServiceClient interface {
	GetSunat(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error)
	GetApp(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	GetSbs(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type addServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAddServiceClient(cc grpc.ClientConnInterface) AddServiceClient {
	return &addServiceClient{cc}
}

func (c *addServiceClient) GetSunat(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.AddService/GetSunat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addServiceClient) GetApp(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.AddService/GetApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addServiceClient) GetSbs(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.AddService/GetSbs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddServiceServer is the server API for AddService service.
type AddServiceServer interface {
	GetSunat(context.Context, *Empty) (*Response, error)
	GetApp(context.Context, *Request) (*Response, error)
	GetSbs(context.Context, *Request) (*Response, error)
}

// UnimplementedAddServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAddServiceServer struct {
}

func (*UnimplementedAddServiceServer) GetSunat(ctx context.Context, req *Empty) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSunat not implemented")
}
func (*UnimplementedAddServiceServer) GetApp(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApp not implemented")
}
func (*UnimplementedAddServiceServer) GetSbs(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSbs not implemented")
}

func RegisterAddServiceServer(s *grpc.Server, srv AddServiceServer) {
	s.RegisterService(&_AddService_serviceDesc, srv)
}

func _AddService_GetSunat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).GetSunat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddService/GetSunat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).GetSunat(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddService_GetApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).GetApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddService/GetApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).GetApp(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddService_GetSbs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).GetSbs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddService/GetSbs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).GetSbs(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AddService",
	HandlerType: (*AddServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSunat",
			Handler:    _AddService_GetSunat_Handler,
		},
		{
			MethodName: "GetApp",
			Handler:    _AddService_GetApp_Handler,
		},
		{
			MethodName: "GetSbs",
			Handler:    _AddService_GetSbs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/service.proto",
}
