// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/proto/updater.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateType int32

const (
	UpdateType_MESSAGES UpdateType = 0
	UpdateType_UPGRADE  UpdateType = 1
)

var UpdateType_name = map[int32]string{
	0: "MESSAGES",
	1: "UPGRADE",
}

var UpdateType_value = map[string]int32{
	"MESSAGES": 0,
	"UPGRADE":  1,
}

func (x UpdateType) String() string {
	return proto.EnumName(UpdateType_name, int32(x))
}

func (UpdateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d587011508eb2449, []int{0}
}

type UpdaterRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdaterRequest) Reset()         { *m = UpdaterRequest{} }
func (m *UpdaterRequest) String() string { return proto.CompactTextString(m) }
func (*UpdaterRequest) ProtoMessage()    {}
func (*UpdaterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d587011508eb2449, []int{0}
}

func (m *UpdaterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdaterRequest.Unmarshal(m, b)
}
func (m *UpdaterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdaterRequest.Marshal(b, m, deterministic)
}
func (m *UpdaterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdaterRequest.Merge(m, src)
}
func (m *UpdaterRequest) XXX_Size() int {
	return xxx_messageInfo_UpdaterRequest.Size(m)
}
func (m *UpdaterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdaterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdaterRequest proto.InternalMessageInfo

func (m *UpdaterRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

type Updater struct {
	Type                 UpdateType `protobuf:"varint,1,opt,name=type,proto3,enum=proto.UpdateType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Updater) Reset()         { *m = Updater{} }
func (m *Updater) String() string { return proto.CompactTextString(m) }
func (*Updater) ProtoMessage()    {}
func (*Updater) Descriptor() ([]byte, []int) {
	return fileDescriptor_d587011508eb2449, []int{1}
}

func (m *Updater) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Updater.Unmarshal(m, b)
}
func (m *Updater) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Updater.Marshal(b, m, deterministic)
}
func (m *Updater) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Updater.Merge(m, src)
}
func (m *Updater) XXX_Size() int {
	return xxx_messageInfo_Updater.Size(m)
}
func (m *Updater) XXX_DiscardUnknown() {
	xxx_messageInfo_Updater.DiscardUnknown(m)
}

var xxx_messageInfo_Updater proto.InternalMessageInfo

func (m *Updater) GetType() UpdateType {
	if m != nil {
		return m.Type
	}
	return UpdateType_MESSAGES
}

func init() {
	proto.RegisterEnum("proto.UpdateType", UpdateType_name, UpdateType_value)
	proto.RegisterType((*UpdaterRequest)(nil), "proto.UpdaterRequest")
	proto.RegisterType((*Updater)(nil), "proto.Updater")
}

func init() {
	proto.RegisterFile("internal/proto/updater.proto", fileDescriptor_d587011508eb2449)
}

var fileDescriptor_d587011508eb2449 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xc9, 0xcc, 0x2b, 0x49,
	0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0x2d, 0x48, 0x49, 0x2c,
	0x49, 0x2d, 0xd2, 0x03, 0xf3, 0x84, 0x58, 0xc1, 0x94, 0x92, 0x1a, 0x17, 0x5f, 0x28, 0x44, 0x3c,
	0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x48, 0x84, 0x8b, 0x35, 0xb1, 0xa0, 0xc0, 0x33, 0x45,
	0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc2, 0x51, 0x32, 0xe0, 0x62, 0x87, 0xaa, 0x13, 0x52,
	0xe5, 0x62, 0x29, 0xa9, 0x2c, 0x48, 0x05, 0xcb, 0xf3, 0x19, 0x09, 0x42, 0xcc, 0xd3, 0x83, 0xc8,
	0x86, 0x54, 0x16, 0xa4, 0x06, 0x81, 0xa5, 0xb5, 0xd4, 0xb9, 0xb8, 0x10, 0x62, 0x42, 0x3c, 0x5c,
	0x1c, 0xbe, 0xae, 0xc1, 0xc1, 0x8e, 0xee, 0xae, 0xc1, 0x02, 0x0c, 0x42, 0xdc, 0x5c, 0xec, 0xa1,
	0x01, 0xee, 0x41, 0x8e, 0x2e, 0xae, 0x02, 0x8c, 0x49, 0x6c, 0x60, 0x03, 0x8c, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x5a, 0xea, 0x9b, 0x0c, 0xb0, 0x00, 0x00, 0x00,
}
